# -*- coding: utf-8 -*-
"""CreateTempData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKnYxTxDafcT5_cEBksPREsljLE54QiT

### Load Temperature
"""

import pandas as pd
import numpy as np

prism_24 = pd.read_csv('PRISM_24.csv', skiprows=10)
prism_25 = pd.read_csv('PRISM_25.csv', skiprows=10)
prism_26 = pd.read_csv('PRISM_26_Apr.csv', skiprows=10)

"""### Fix HI AK"""

other_states = pd.read_csv('AK_HI_data.csv')

"""#### Get Alaska Hawaii Data"""

Ak_Hi_data = other_states[other_states['state'].isin(['AK', 'HI'])]

Ak_Hi_data.to_csv('AK_HI_data.csv', index=False)

other_states.rename(columns={'week_start': 'Date', 'weekly_average_temp': 'average_temp', 'weekly_rainfall': 'rainfall'}, inplace=True)

other_states.columns

other_states.drop(columns=['source'], inplace=True)

other_states

"""#### Merge Prism"""

full_data = pd.concat([prism_24, prism_25, prism_26])

full_data['state'] = full_data['Name'].str.split(', ').str[1]

full_data.rename(columns={'ppt (inches)': 'rainfall', 'tmean (degrees F)': 'average_temp'}, inplace=True)

full_data.drop(columns=['Name', 'Longitude', 'Latitude', 'Elevation (ft)'], inplace=True)

full_data.head()

"""#### Merge Prism with HI AK"""

full_data = pd.concat([full_data, other_states])

"""#### Agg Daily"""

daily_state_summary = full_data.groupby(['Date', 'state']).agg(
    average_temp=('average_temp', 'mean'),
    rainfall=('rainfall', 'mean')
).reset_index()

daily_state_summary.head()

"""#### Convert Date to Datetime and Calculate Week Start

#### Correct Week Start Calculation
"""

daily_state_summary['Date'] = pd.to_datetime(daily_state_summary['Date'])
daily_state_summary['week_start'] = daily_state_summary['Date'] - pd.to_timedelta(daily_state_summary['Date'].dt.weekday, unit='D')
daily_state_summary.head()

other_states['Date'] = pd.to_datetime(other_states['Date'])
other_states['week_start'] = other_states['Date'] - pd.to_timedelta(other_states['Date'].dt.weekday, unit='D')
other_states.head()

"""**Reasoning**:
The next step is to re-aggregate the `daily_state_summary` DataFrame using the newly corrected `week_start` column. This aggregation involves calculating the mean of 'average_temp' and the sum of 'rainfall' grouped by 'state' and 'week_start', as per the main task's requirements.


"""

weekly_summary = daily_state_summary.groupby(['state', 'week_start']).agg(
    weekly_average_temp=('average_temp', 'mean'),
    weekly_rainfall=('rainfall', 'sum')
).reset_index()
weekly_summary.head()

weekly_summary

weekly_summary = pd.concat([weekly_summary, other_states])

weekly_summary.tail()



weekly_summary.to_csv('weekly_temp_data_Apr26.csv')